### ISSUE TITLE
[BUG]: DOMException [DataError]: Zero-length key is not supported

### ISSUE THREAD

**Issue by damidani** [fonoster/fonoster#741]
### What happened?

When I want to access the web interface, I'm stuck on Loading Fonoster Services... Please wait.

### Steps to reproduce

Log docker 

dashboard-1  | DOMException [DataError]: Zero-length key is not supported
dashboard-1  |     at Object.hmacImportKey (node:internal/crypto/mac:103:15)
dashboard-1  |     at SubtleCrypto.importKey (node:internal/crypto/webcrypto:636:10)
dashboard-1  |     at createKey2 (file:///app/node_modules/react-router/dist/development/chunk-NL6KNZEE.mjs:10000:58)
dashboard-1  |     at sign (file:///app/node_modules/react-router/dist/development/chunk-NL6KNZEE.mjs:9982:19)
dashboard-1  |     at encodeCookieValue (file:///app/node_modules/react-router/dist/development/chunk-NL6KNZEE.mjs:10066:21)
dashboard-1  |     at Object.serialize (file:///app/node_modules/react-router/dist/development/chunk-NL6KNZEE.mjs:10051:35)
dashboard-1  |     at commitSession (file:///app/node_modules/react-router/dist/development/chunk-NL6KNZEE.mjs:11323:43)
dashboard-1  |     at rootAuthLoader (file:///app/build/server/index.js:24914:38)
dashboard-1  |     at callRouteHandler (file:///app/node_modules/react-router/dist/development/chunk-NL6KNZEE.mjs:10240:16)
dashboard-1  |     at commonRoute.loader (file:///app/node_modules/react-router/dist/development/chunk-NL6KNZEE.mjs:10389:19)
dashboard-1  | GET /auth/login.data 500 - - 7.200 ms

### Expected behavior

The connection system should be displayed

**Comment by SSIvanov19** [comment]
I fixed this issue by adding SERVER_DASHBOARD_SESSION_SECRET env variable to dashboard's compose section.
So my compose.yaml is:
```
services:
  dashboard:
    image: fonoster/dashboard:latest
    restart: unless-stopped
    expose:
      - 3030:3030
    environment:
      - DASHBOARD_API_URL
      - DASHBOARD_AUTH_GITHUB_ENABLED=false
      - DASHBOARD_AUTH_GITHUB_CLIENT_ID
      - DASHBOARD_AUTH_GITHUB_URL
      - DASHBOARD_EDITION
      - SERVER_DASHBOARD_SESSION_SECRET=${SESSION_SECRET}
...  the rest of the compose.yaml
```
and I add SESSION_SECRET to my .env file:
```.env
SESSION_SECRET=<random generated string of symbols to be used as a secret>
```
Hope that helps
